In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

import joblib

Matplotlib is building the font cache; this may take a moment.

In [5]:
import os
print(os.getcwd())

c:\Users\biren\OneDrive\Desktop\aiml intenship

In [7]:
import os

print("Current Folder:")
print(os.getcwd())

print("\nFiles:")
print(os.listdir())

Current Folder:
c:\Users\biren\OneDrive\Desktop\aiml intenship

Files:
['.git', 'aiml', 'app.py', 'bp.csv', 'House_Rent_Dataset.csv', 'house_rent_pipeline.pkl', 'house_rent_prediction.pkl', 'hpp.py', 'performance.ipynb', 'requirements.txt', 'runtime.txt', 'student_performance (2).csv', 'test.ipynb', 'test2.ipynb', 'test3.ipynb', 'tst.py', 'wine.csv']

In [8]:
import pandas as pd

data = pd.read_csv("student_performance (2).csv")
data.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Attendance,Performance Index
0,7,64,7,4,70,72.8
1,10,71,8,6,75,85.5
2,3,78,9,8,80,78.1
3,6,85,5,10,85,86.8
4,9,92,6,1,90,91.7

In [9]:
data.shape

(200, 6)

In [10]:
data.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Attendance,Performance Index
0,7,64,7,4,70,72.8
1,10,71,8,6,75,85.5
2,3,78,9,8,80,78.1
3,6,85,5,10,85,86.8
4,9,92,6,1,90,91.7

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     200 non-null    int64
 1   Previous Scores                   200 non-null    int64
 2   Sleep Hours                       200 non-null    int64
 3   Sample Question Papers Practiced  200 non-null    int64
 4   Attendance                        200 non-null    int64
 5   Performance Index                 200 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 9.5 KB

In [12]:
data.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Attendance,Performance Index
count,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000
mean,5.500000,75.06000,7.000000,5.000000,80.010000,78.373500
std,2.879489,14.65607,1.417762,3.155915,11.790035,9.452396
min,1.000000,50.00000,5.000000,0.000000,60.000000,55.900000
25%,3.000000,62.75000,6.000000,2.000000,70.000000,71.300000
50%,5.500000,75.00000,7.000000,5.000000,80.000000,78.800000
75%,8.000000,88.00000,8.000000,8.000000,90.000000,85.125000
max,10.000000,100.00000,9.000000,10.000000,100.000000,100.000000

In [13]:
data.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Sleep Hours                         0
Sample Question Papers Practiced    0
Attendance                          0
Performance Index                   0
dtype: int64

In [14]:
data.duplicated().sum()

np.int64(0)

In [15]:
data.shape

(200, 6)

In [16]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced', 'Attendance', 'Performance Index'],
      dtype='str')

In [17]:
X = data.drop("Performance Index", axis=1)
y = data["Performance Index"]

In [18]:
X.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Attendance
0,7,64,7,4,70
1,10,71,8,6,75
2,3,78,9,8,80
3,6,85,5,10,85
4,9,92,6,1,90

In [19]:
y.head()

0    72.8
1    85.5
2    78.1
3    86.8
4    91.7
Name: Performance Index, dtype: float64

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (160, 5)
X_test: (40, 5)
y_train: (160,)
y_test: (40,)

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

pipeline

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [23]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [24]:
y_pred = pipeline.predict(X_test)

In [25]:
from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score :", r2_score(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))

R2 Score : 0.9999864062472831
MAE : 0.025775524756987522

In [26]:
import pandas as pd

result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

result.head(10)

   Actual  Predicted
0    75.2  75.194633
1    59.0  58.957149
2    89.2  89.190087
3    73.8  73.749786
4    81.5  81.440863
5    58.7  58.655806
6    85.4  85.388137
7    90.0  90.045417
8    74.7  74.707020
9    75.3  75.345305

In [27]:
import joblib

joblib.dump(pipeline, "student_pipeline.pkl")

print("Model Saved Successfully!")

Model Saved Successfully!

In [28]:
sample = pd.DataFrame({
    "Hours Studied": [8],
    "Previous Scores": [85],
    "Sleep Hours": [7],
    "Sample Question Papers Practiced": [5],
    "Attendance": [90]
})

prediction = pipeline.predict(sample)

print("Predicted Performance Index:", prediction[0])

Predicted Performance Index: 90.84353620772912